pages:
  image: node:12.13
  stage: deploy
  cache:
    paths:
      - /node_modules
  script:
    - yarn
    - yarn build
    - mv static public
  artifacts:
    paths:
      - public
  only:
    - master
